apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["10.1.1.43"],"port":32000,"protocol":"TCP","serviceName":"default:database-nodeport","allNodes":true}]'
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/8RX32/bthP/Xw74vkmOJNuxpbd8m7Z7aFcvdjuscTFQ4snhQpEaSbk1DP/vA6kflhRnLbAMg198x+P9vvtQRyAl+4RKMykgAVKW+mofggePTFBI4BZLLg8FCgMeFGgIJYZAcgQihDTEMCm0JWknN3msUlQCDeoJk1cK96xRbtXmDDmdZMQYjva4rFLOsteClpIJoyGB++MWCKUKtUa9heR+C2EwCe1vPt/CF28LpVRmC8k0CoLAkkoamUm+hWQLm1erLXhb0Kj24IFM/8DMaDQTxWTPLrPBhfMgjmgQ+XOMp/5skaU+icjcxzhP5yQP5nSawsmDTKGLdMMK1IYUJSQQBVHkh5EfLjfhPAniZLb4DB7sUKBywpBEHnCSIncJes6RB6IfIIEZWUbXy+twEYfxMqfhdDal4XSRx/N8mcUzEmRRtMijGXjwVapHLgmdVBpVT1PL18gxM1I15ZycS+NTzEnFjW+LmBKNNriCCLJD+sYWRkNy/2xHuNLpzaFESKAW/3TmfwptlHnS75E8GXVJnny3/sfTyYM8OSduYnmW9eNxH0+1El1iVpstldzZjrpFQjkTuMZMCqpb1QpLzjLSo+um/YlpI9XhHSuYac/6ZhxtFDG4O9SGlOScid3HkhKDA/cL8m1dqR326I+C7AnjJOXYBW5cflsCi5I3isapfeEMkTxngplDqyuTwhAmUDkTj8lxC4IU6GasO/ODLZwGLqDY9+jhtfe/rX959/vtzebm/zfr1+ObVqz9vye8arNwScfqZr3+9cPd7T/Rcffhw+ZFFH1cv777sfuOZAU5N4EjVhXnK8lZdrh03S47Pc5pV4FVswqnwfXFTTh0a3DtorFGwdldhVpWKsNuNgyqggk30+9Ra+s/MQ9/c9pFViukQg+DVXanKjNk6uwBacVR/dzzTmNWKWYOr6Qw+M1csPlWkQxXqJikvRE/OdP1onNrcVfjmSy7XQ3NxHpgmDV4Yb8vP8PJ+ze3Y1emHwDTboANMVWzW7tlcjdaZzYRbGzG9ZHdNq5Zbtq745bhRJuNIkKzFgH7J3XW+tyirvq5uETX/g68Ha+6oTOrZlszsfsv3HGUTO0LAunbHqB3OuhhnOIxglTOE9oXG/agLaxv59EiBiq/PXmmK3WVtpMICTSOP9OsYZAEi89w+uJBPdvQ4X3N0SVxaprnAHhQufdQHme4XKSxHy3j3J9dz2I/nl3H/jKLFnGYBWQaUftkaFHjWVS9DgIPzikJLXEJUcPAgx4oQUFM9vCuA7YXfelYv3tQ/QSoz/gM0fx/9rU7AmjHPnlQ9wncDRRYfg+s+3N+4fUoKs77j8MXD7Qp0BDU+5B+fwQH1ffHtkeG6AweNLgFBrVxm28gaFGvJ2QdfyrUwmtPsCRaf5WKPhUeAHLvhpLSuGZukBOKg/6TJzbV2vbuEwyFG/6VHDR07d97r4AHDaDeH2EEhw5E2zuWMFnpvjHspQ4YLa46d0bI+BwuwhXF/VXv1OdyBxflW//fMI7ORA8r4RWvtEH1hikX9Qg1zzGPkLMdcr/jW5lLQPodGJ0GFkb/CgAA//9zJU3KMA4AAA
    objectset.rio.cattle.io/id: 15092d02-5e93-47cb-a2a5-e9fb5af05d3b
  generation: 3
  labels:
    objectset.rio.cattle.io/hash: 4a82686179198fd1343d137f95f8c94a0c227f24
    workload.user.cattle.io/workloadselector: apps.deployment-default-database
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
          f:field.cattle.io/publicEndpoints: {}
          f:objectset.rio.cattle.io/applied: {}
          f:objectset.rio.cattle.io/id: {}
        f:labels:
          .: {}
          f:objectset.rio.cattle.io/hash: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:affinity: {}
            f:containers:
              k:{"name":"container-0"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"MYSQL_DATABASE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MYSQL_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MYSQL_ROOT_PASSWORD"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"MYSQL_USER"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":3306,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: agent
    operation: Update
    time: "2022-12-18T23:01:24Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2022-12-18T23:01:41Z"
  name: database
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-database
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-database
    spec:
      affinity: {}
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: test
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:latest
        imagePullPolicy: Always
        name: container-0
        ports:
        - containerPort: 3306
          name: 3306tcp32000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
