version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '13306:3306'
    expose:
      # Opens port 3306 on the container
      - '13306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  payment_checkout_api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      SQLALCHEMY_DATABASE_URL: "mysql+pymysql://root:root@db:3306/test"
      WEBHOOK_URL: "INSERT-WEBHOOK-URL-HERE!!"
    ports:
      - 8000:8000
    depends_on:
      - db
  # user_profile:
  #   build:
  #     context: ./webApp/payment-web/
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4200:4200
  #   depends_on:
  #     - db
  #     - payment_checkout_api
  # Names our volume
volumes:
  my-db:
